"""
Billing Dashboard Generator.

Generates a self-contained HTML dashboard for on-demand usage billing analytics.
"""

from datetime import datetime
from pathlib import Path
from typing import List

from .billing_calculator import BillingMetrics, ModelStats, UserStats, MonthlyBreakdown
from .utils import get_data_path


def _fmt_dollars(cents: float) -> str:
    """Format cents as dollar string."""
    return f"${cents / 100:,.2f}"


def _fmt_number(value: int) -> str:
    """Format integer with thousands separator."""
    return f"{value:,}"


def _fmt_tokens(value: int) -> str:
    """Format token count with K/M/B suffix."""
    if value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.1f}B"
    if value >= 1_000_000:
        return f"{value / 1_000_000:.1f}M"
    if value >= 1_000:
        return f"{value / 1_000:.1f}K"
    return str(value)


class BillingDashboardGenerator:
    """Generates HTML billing dashboard from BillingMetrics."""

    def __init__(self, output_filename: str = "billing_dashboard.html"):
        self.output_filename = output_filename

    def generate(self, metrics: BillingMetrics, top_count: int = 20) -> str:
        """
        Generate the HTML dashboard and write to file.

        Returns:
            str: Path to the generated HTML file
        """
        html = self._build_html(metrics, top_count)
        output_path = get_data_path() / self.output_filename
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        return str(output_path)

    def _build_html(self, metrics: BillingMetrics, top_count: int) -> str:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>On-Demand Billing Analytics - Cursor IDE</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="header">
        <div class="container">
            <h1>On-Demand Billing Analytics</h1>
            <p>Cursor IDE Usage-Based Cost Dashboard</p>
            <p>Generated on {timestamp}</p>
        </div>
    </div>

    <div class="container">
        {self._build_summary_cards(metrics)}
        {self._build_top_users_section(metrics, top_count)}
        {self._build_users_by_model_section(metrics, top_count)}
        {self._build_top_models_section(metrics, top_count)}
        {self._build_monthly_trend_section(metrics)}
        {self._build_monthly_ondemand_users(metrics)}
        {self._build_monthly_model_breakdown(metrics)}
    </div>

    <div class="footer">
        <p>Generated by AI Adoption Analytics | Success Measurement Project</p>
        <p>Data source: Cursor Admin API (/teams/filtered-usage-events)</p>
        <p>Cost = tokenUsage.totalCents + cursorTokenFee | Filter: kind=Usage-based, isChargeable=true</p>
    </div>
</body>
</html>"""

    def _get_styles(self) -> str:
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f7fa;
            color: #333;
            line-height: 1.6;
        }

        .header {
            background: linear-gradient(135deg, #e74c3c 0%, #c0392b 100%);
            color: white;
            text-align: center;
            padding: 2rem 0;
            margin-bottom: 2rem;
        }

        .header h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
        .header p { font-size: 1.1rem; opacity: 0.9; }

        .container { max-width: 1400px; margin: 0 auto; padding: 0 1rem; }

        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 1.5rem;
            margin-bottom: 2rem;
        }

        .summary-card {
            background: white;
            border-radius: 10px;
            padding: 1.5rem;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.3s ease;
        }

        .summary-card:hover { transform: translateY(-5px); }
        .summary-card h3 { color: #e74c3c; margin-bottom: 0.5rem; font-size: 0.95rem; }
        .summary-card .number { font-size: 2.2rem; font-weight: bold; color: #333; margin-bottom: 0.5rem; }
        .summary-card p { color: #666; font-size: 0.85rem; }

        .section {
            background: white;
            border-radius: 10px;
            margin-bottom: 2rem;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            overflow: hidden;
        }

        .section-header {
            padding: 1.5rem;
            font-size: 1.3rem;
            font-weight: bold;
            color: white;
        }

        .section-content { padding: 1.5rem; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; }
        th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #e0e0e0; }
        th { background: #f8f9fa; font-weight: 600; color: #333; }
        tr:hover { background: #f8f9fa; }

        .cost-cell {
            text-align: right;
            font-family: 'Courier New', monospace;
            font-weight: bold;
            color: #e74c3c;
        }

        .number-cell {
            text-align: right;
            font-family: 'Courier New', monospace;
            color: #555;
        }

        .rank-cell { font-weight: bold; width: 60px; }

        .trend-positive { color: #e74c3c; }
        .trend-negative { color: #27ae60; }

        .subsection {
            margin-bottom: 1.5rem;
            padding-bottom: 1.5rem;
            border-bottom: 1px solid #eee;
        }

        .subsection:last-child { border-bottom: none; }

        .subsection h4 {
            color: #333;
            margin-bottom: 0.75rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid #e74c3c;
        }

        .info-box {
            background: #fef5f5;
            border: 1px solid #f5c6cb;
            border-radius: 8px;
            padding: 1rem;
            margin-top: 1rem;
        }

        .info-box p { color: #721c24; margin-bottom: 0.3rem; font-size: 0.9rem; }

        .footer {
            text-align: center;
            padding: 2rem;
            color: #666;
            border-top: 1px solid #e0e0e0;
            margin-top: 2rem;
        }

        .footer p { font-size: 0.85rem; margin-bottom: 0.3rem; }

        @media (max-width: 768px) {
            .header h1 { font-size: 1.8rem; }
            .summary-cards { grid-template-columns: repeat(2, 1fr); }
            table { font-size: 0.85rem; }
            th, td { padding: 0.5rem; }
        }
        """

    def _build_summary_cards(self, metrics: BillingMetrics) -> str:
        top_model = metrics.top_cost_model
        top_spender = metrics.top_spender_email
        top_spender_display = top_spender.split("@")[0].replace(".", " ").title() if "@" in top_spender else top_spender

        current = metrics.monthly_breakdowns[-1] if metrics.monthly_breakdowns else None
        current_cost = _fmt_dollars(current.total_cost_cents) if current else "$0.00"
        current_label = current.month_label if current else "N/A"

        return f"""
        <div class="summary-cards">
            <div class="summary-card">
                <h3>Total On-Demand Spend</h3>
                <div class="number">{_fmt_dollars(metrics.total_cost_cents)}</div>
                <p>Across {metrics.months_analyzed} month(s)</p>
            </div>
            <div class="summary-card">
                <h3>Current Month</h3>
                <div class="number">{current_cost}</div>
                <p>{current_label}</p>
            </div>
            <div class="summary-card">
                <h3>Total Requests</h3>
                <div class="number">{_fmt_number(metrics.total_requests)}</div>
                <p>Usage-based chargeable</p>
            </div>
            <div class="summary-card">
                <h3>Costliest Model</h3>
                <div class="number" style="font-size: 1.2rem;">{top_model}</div>
                <p>{_fmt_dollars(metrics.model_stats[top_model].total_cost_cents) if top_model in metrics.model_stats else ''}</p>
            </div>
            <div class="summary-card">
                <h3>Top Spender</h3>
                <div class="number" style="font-size: 1.4rem;">{top_spender_display}</div>
                <p>{_fmt_dollars(metrics.user_stats[top_spender].total_cost_cents) if top_spender in metrics.user_stats else ''}</p>
            </div>
        </div>
        """

    def _build_top_users_section(self, metrics: BillingMetrics, top_count: int) -> str:
        """Priority 1: Top cost users."""
        top_users = metrics.get_top_users(top_count)
        if not top_users:
            return ""

        rows = ""
        for rank, user in enumerate(top_users, 1):
            display_name = user.email.split("@")[0].replace(".", " ").title()
            rows += f"""
            <tr>
                <td class="rank-cell">{rank}</td>
                <td>{display_name}</td>
                <td style="color: #666; font-size: 0.85rem;">{user.email}</td>
                <td class="cost-cell">{_fmt_dollars(user.total_cost_cents)}</td>
                <td class="number-cell">{_fmt_number(user.total_requests)}</td>
                <td>{user.top_model}</td>
                <td class="number-cell">{_fmt_dollars(user.avg_cost_per_request_cents)}</td>
            </tr>
            """

        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #e74c3c, #c0392b);">
                UseCase 1: Top Cost Users
            </div>
            <div class="section-content">
                <table>
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Total Spend</th>
                            <th>Requests</th>
                            <th>Top Model</th>
                            <th>Avg Cost/Req</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
                <div class="info-box">
                    <p><strong>Scope:</strong> Cumulative on-demand spend across all analyzed months</p>
                    <p><strong>Cost formula:</strong> tokenUsage.totalCents + cursorTokenFee</p>
                </div>
            </div>
        </div>
        """

    def _build_users_by_model_section(self, metrics: BillingMetrics, top_count: int) -> str:
        """Priority 2: For each expensive model, which users drove the cost."""
        top_models = metrics.get_top_models(5)
        if not top_models:
            return ""

        subsections = ""
        for model_stat in top_models:
            user_data = metrics.get_users_for_model(model_stat.model, top_count)
            if not user_data:
                continue

            rows = ""
            for rank, (email, cost_cents, req_count) in enumerate(user_data, 1):
                display_name = email.split("@")[0].replace(".", " ").title()
                rows += f"""
                <tr>
                    <td class="rank-cell">{rank}</td>
                    <td>{display_name}</td>
                    <td style="color: #666; font-size: 0.85rem;">{email}</td>
                    <td class="cost-cell">{_fmt_dollars(cost_cents)}</td>
                    <td class="number-cell">{_fmt_number(req_count)}</td>
                </tr>
                """

            subsections += f"""
            <div class="subsection">
                <h4>{model_stat.model} (Total: {_fmt_dollars(model_stat.total_cost_cents)})</h4>
                <table>
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Spend on Model</th>
                            <th>Requests</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>
            """

        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #e67e22, #d35400);">
                UseCase 2: Users by Expensive Model
            </div>
            <div class="section-content">
                {subsections}
                <div class="info-box">
                    <p><strong>Insight:</strong> Which users are driving costs on the most expensive models</p>
                </div>
            </div>
        </div>
        """

    def _build_top_models_section(self, metrics: BillingMetrics, top_count: int) -> str:
        """Priority 3: Top cost models."""
        top_models = metrics.get_top_models(top_count)
        if not top_models:
            return ""

        rows = ""
        for rank, m in enumerate(top_models, 1):
            rows += f"""
            <tr>
                <td class="rank-cell">{rank}</td>
                <td>{m.model}</td>
                <td class="cost-cell">{_fmt_dollars(m.total_cost_cents)}</td>
                <td class="number-cell">{_fmt_number(m.total_requests)}</td>
                <td class="number-cell">{_fmt_tokens(m.total_tokens)}</td>
                <td class="number-cell">{_fmt_dollars(m.avg_cost_per_request_cents)}</td>
                <td class="number-cell">{len(m.unique_users)}</td>
            </tr>
            """

        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #8e44ad, #7d3c98);">
                UseCase 3: Top Cost Models
            </div>
            <div class="section-content">
                <table>
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Model</th>
                            <th>Total Cost</th>
                            <th>Requests</th>
                            <th>Tokens</th>
                            <th>Avg Cost/Req</th>
                            <th>Users</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>
        </div>
        """

    def _build_monthly_trend_section(self, metrics: BillingMetrics) -> str:
        """Monthly billing trend with deltas."""
        breakdowns = metrics.monthly_breakdowns
        if not breakdowns:
            return ""

        rows = ""
        for i, bd in enumerate(breakdowns):
            delta = ""
            if i > 0:
                prev = breakdowns[i - 1].total_cost_cents
                if prev > 0:
                    pct = ((bd.total_cost_cents - prev) / prev) * 100
                    sign = "+" if pct >= 0 else ""
                    css_class = "trend-positive" if pct >= 0 else "trend-negative"
                    delta = f'<span class="{css_class}">{sign}{pct:.1f}%</span>'

            rows += f"""
            <tr>
                <td>{bd.month_label}</td>
                <td class="cost-cell">{_fmt_dollars(bd.total_cost_cents)}</td>
                <td class="number-cell">{_fmt_number(bd.total_requests)}</td>
                <td class="number-cell">{len(bd.user_costs)}</td>
                <td class="number-cell">{len(bd.model_costs)}</td>
                <td class="number-cell">{delta}</td>
            </tr>
            """

        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #2c3e50, #34495e);">
                Monthly Billing Trend
            </div>
            <div class="section-content">
                <table>
                    <thead>
                        <tr>
                            <th>Month</th>
                            <th>Total On-Demand Cost</th>
                            <th>Requests</th>
                            <th>Active Spenders</th>
                            <th>Models Used</th>
                            <th>vs Previous</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>
        </div>
        """

    def _build_monthly_ondemand_users(self, metrics: BillingMetrics) -> str:
        """Per-month list of ALL users who incurred on-demand usage."""
        breakdowns = metrics.monthly_breakdowns
        if not breakdowns:
            return ""

        subsections = ""
        for bd in breakdowns:
            sorted_users = sorted(bd.user_costs.items(), key=lambda x: x[1], reverse=True)
            user_count = len(sorted_users)

            rows = ""
            for rank, (email, cost_cents) in enumerate(sorted_users, 1):
                display_name = email.split("@")[0].replace(".", " ").title()
                reqs = bd.user_requests.get(email, 0)

                rows += f"""
                <tr>
                    <td class="rank-cell">{rank}</td>
                    <td>{display_name}</td>
                    <td style="color: #666; font-size: 0.85rem;">{email}</td>
                    <td class="cost-cell">{_fmt_dollars(cost_cents)}</td>
                    <td class="number-cell">{_fmt_number(reqs)}</td>
                </tr>
                """

            subsections += f"""
            <div class="subsection">
                <h4>{bd.month_label} &mdash; {user_count} user(s) with on-demand usage</h4>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>On-Demand Spend</th>
                            <th>Requests</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>
            """

        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #16a085, #1abc9c);">
                Monthly On-Demand Users
            </div>
            <div class="section-content">
                {subsections}
                <div class="info-box">
                    <p><strong>Who is listed?</strong> Only users who exceeded their 1,000 included requests and incurred on-demand (usage-based) charges during each month.</p>
                    <p>Users who stayed within their license allocation are not shown.</p>
                </div>
            </div>
        </div>
        """

    def _build_monthly_model_breakdown(self, metrics: BillingMetrics) -> str:
        """Per-month model cost breakdown matching Cursor Dashboard layout."""
        breakdowns = metrics.monthly_breakdowns
        if not breakdowns:
            return ""

        subsections = ""
        for bd in breakdowns:
            sorted_models = sorted(bd.model_costs.items(), key=lambda x: x[1], reverse=True)
            rows = ""
            for model_name, cost_cents in sorted_models:
                reqs = bd.model_requests.get(model_name, 0)
                tokens = bd.model_tokens.get(model_name, 0)
                avg = cost_cents / reqs if reqs > 0 else 0

                rows += f"""
                <tr>
                    <td>{model_name}</td>
                    <td class="number-cell">{_fmt_tokens(tokens)}</td>
                    <td class="number-cell">{_fmt_dollars(avg)}</td>
                    <td class="number-cell">{_fmt_number(reqs)}</td>
                    <td class="cost-cell">{_fmt_dollars(cost_cents)}</td>
                </tr>
                """

            subsections += f"""
            <div class="subsection">
                <h4>{bd.month_label} ({_fmt_dollars(bd.total_cost_cents)})</h4>
                <table>
                    <thead>
                        <tr>
                            <th>Model</th>
                            <th>Tokens</th>
                            <th>Avg Cost/Req</th>
                            <th>Requests</th>
                            <th>Total Cost</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>
            """

        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #2196F3, #1976D2);">
                Monthly Model Breakdown
            </div>
            <div class="section-content">
                {subsections}
            </div>
        </div>
        """

    def _build_monthly_user_breakdown(self, metrics: BillingMetrics, top_count: int) -> str:
        """Per-month top spenders."""
        breakdowns = metrics.monthly_breakdowns
        if not breakdowns:
            return ""

        subsections = ""
        for bd in breakdowns:
            sorted_users = sorted(bd.user_costs.items(), key=lambda x: x[1], reverse=True)[:top_count]
            rows = ""
            for rank, (email, cost_cents) in enumerate(sorted_users, 1):
                display_name = email.split("@")[0].replace(".", " ").title()
                reqs = bd.user_requests.get(email, 0)
                user_models = bd.user_top_model.get(email, {})
                top_model = max(user_models, key=user_models.get) if user_models else "N/A"

                rows += f"""
                <tr>
                    <td class="rank-cell">{rank}</td>
                    <td>{display_name}</td>
                    <td style="color: #666; font-size: 0.85rem;">{email}</td>
                    <td class="cost-cell">{_fmt_dollars(cost_cents)}</td>
                    <td class="number-cell">{_fmt_number(reqs)}</td>
                    <td>{top_model}</td>
                </tr>
                """

            subsections += f"""
            <div class="subsection">
                <h4>{bd.month_label} ({_fmt_dollars(bd.total_cost_cents)})</h4>
                <table>
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>On-Demand Spend</th>
                            <th>Requests</th>
                            <th>Top Model</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>
            """

        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #27ae60, #229954);">
                Monthly User Breakdown
            </div>
            <div class="section-content">
                {subsections}
            </div>
        </div>
        """
