"""
Dashboard Generator for AI Adoption Analytics.

Generates an HTML dashboard displaying adoption metrics.
"""

from datetime import datetime
from pathlib import Path
from typing import List

from .metrics_calculator import AdoptionMetrics, InactiveUserInfo
from .csv_processor import MonthlyStats
from .utils import format_number, get_data_path


class DashboardGenerator:
    """
    Generates HTML dashboard for AI adoption metrics.
    """
    
    def __init__(self, output_filename: str = "adoption_dashboard.html"):
        """
        Initialize the dashboard generator.
        
        Args:
            output_filename: Name of output HTML file
        """
        self.output_filename = output_filename
    
    def generate(self, metrics: AdoptionMetrics) -> str:
        """
        Generate the HTML dashboard.
        
        Args:
            metrics: Calculated AdoptionMetrics
            
        Returns:
            str: Path to generated HTML file
        """
        html_content = self._build_html(metrics)
        
        output_path = get_data_path() / self.output_filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        return str(output_path)
    
    def _build_html(self, metrics: AdoptionMetrics) -> str:
        """Build the complete HTML document."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Adoption Analytics - Cursor IDE Dashboard</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="header">
        <div class="container">
            <h1>AI Adoption Analytics</h1>
            <p>Cursor IDE Usage Dashboard</p>
            <p>Generated on {timestamp} | Reference Date: {metrics.reference_date}</p>
        </div>
    </div>

    <div class="container">
        {self._build_summary_cards(metrics)}
        {self._build_team_section(metrics)}
        {self._build_monthly_usage_section(metrics)}
        {self._build_top_users_section(metrics)}
        {self._build_inactive_users_section(metrics)}
    </div>

    <div class="footer">
        <p>Generated by AI Adoption Analytics | Success Measurement Project</p>
        <p>Data sources: Cursor Admin API & Monthly Usage CSV Exports</p>
    </div>
</body>
</html>"""
    
    def _get_styles(self) -> str:
        """Return CSS styles for the dashboard."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f7fa;
            color: #333;
            line-height: 1.6;
        }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-align: center;
            padding: 2rem 0;
            margin-bottom: 2rem;
        }
        
        .header h1 {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }
        
        .header p {
            font-size: 1.1rem;
            opacity: 0.9;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 1rem;
        }
        
        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1.5rem;
            margin-bottom: 2rem;
        }
        
        .summary-card {
            background: white;
            border-radius: 10px;
            padding: 1.5rem;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            text-align: center;
            transition: transform 0.3s ease;
        }
        
        .summary-card:hover {
            transform: translateY(-5px);
        }
        
        .summary-card h3 {
            color: #667eea;
            margin-bottom: 0.5rem;
            font-size: 0.95rem;
        }
        
        .summary-card .number {
            font-size: 2.5rem;
            font-weight: bold;
            color: #333;
            margin-bottom: 0.5rem;
        }
        
        .summary-card p {
            color: #666;
            font-size: 0.85rem;
        }
        
        .section {
            background: white;
            border-radius: 10px;
            margin-bottom: 2rem;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }
        
        .section-header {
            padding: 1.5rem;
            font-size: 1.3rem;
            font-weight: bold;
            color: white;
        }
        
        .section-content {
            padding: 1.5rem;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 1rem;
        }
        
        th, td {
            padding: 0.75rem 1rem;
            text-align: left;
            border-bottom: 1px solid #e0e0e0;
        }
        
        th {
            background: #f8f9fa;
            font-weight: 600;
            color: #333;
        }
        
        tr:hover {
            background: #f8f9fa;
        }
        
        .user-list {
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
            margin-bottom: 1rem;
        }
        
        .user-chip {
            background: #e3f2fd;
            color: #1565c0;
            padding: 0.4rem 0.8rem;
            border-radius: 20px;
            font-size: 0.85rem;
        }
        
        .user-chip.owner {
            background: #fff3e0;
            color: #e65100;
        }
        
        .user-chip.removed {
            background: #ffebee;
            color: #c62828;
            text-decoration: line-through;
        }
        
        .user-chip.inactive {
            background: #fce4ec;
            color: #c2185b;
        }
        
        .info-box {
            background: #e3f2fd;
            border: 1px solid #90caf9;
            border-radius: 8px;
            padding: 1rem;
            margin-top: 1rem;
        }
        
        .info-box p {
            color: #1565c0;
            margin-bottom: 0.3rem;
            font-size: 0.9rem;
        }
        
        .warning-box {
            background: #fff3e0;
            border: 1px solid #ffb74d;
            border-radius: 8px;
            padding: 1rem;
            margin-top: 1rem;
        }
        
        .warning-box p {
            color: #e65100;
            margin-bottom: 0.3rem;
            font-size: 0.9rem;
        }
        
        .rank-cell {
            font-weight: bold;
            width: 60px;
        }
        
        .requests-cell {
            text-align: right;
            font-family: 'Courier New', monospace;
            font-weight: bold;
            color: #667eea;
        }
        
        .subsection {
            margin-bottom: 1.5rem;
        }
        
        .subsection h4 {
            color: #333;
            margin-bottom: 0.75rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid #667eea;
        }
        
        .footer {
            text-align: center;
            padding: 2rem;
            color: #666;
            border-top: 1px solid #e0e0e0;
            margin-top: 2rem;
        }
        
        @media (max-width: 768px) {
            .header h1 {
                font-size: 1.8rem;
            }
            .summary-cards {
                grid-template-columns: repeat(2, 1fr);
            }
        }
        """
    
    def _build_summary_cards(self, metrics: AdoptionMetrics) -> str:
        """Build the summary cards section."""
        # Calculate adoption rate (30-day active)
        active_in_30_days = metrics.active_members_count - len(metrics.inactive_30_days)
        adoption_rate = (active_in_30_days / metrics.active_members_count * 100) if metrics.active_members_count > 0 else 0
        
        return f"""
        <div class="summary-cards">
            <div class="summary-card">
                <h3>Total Team Members</h3>
                <div class="number">{metrics.active_members_count}</div>
                <p>With active access</p>
            </div>
            <div class="summary-card">
                <h3>Active Users (30 days)</h3>
                <div class="number">{active_in_30_days}</div>
                <p>{adoption_rate:.1f}% adoption rate</p>
            </div>
            <div class="summary-card">
                <h3>Team Owners</h3>
                <div class="number">{metrics.owners_count}</div>
                <p>Admin access</p>
            </div>
            <div class="summary-card">
                <h3>Total Requests</h3>
                <div class="number">{format_number(metrics.total_requests_all_time, 1)}</div>
                <p>All time</p>
            </div>
            <div class="summary-card">
                <h3>Removed Members</h3>
                <div class="number">{metrics.removed_members_count}</div>
                <p>Access revoked</p>
            </div>
        </div>
        """
    
    def _build_team_section(self, metrics: AdoptionMetrics) -> str:
        """Build the team members section."""
        # Build owner chips
        owner_chips = "".join([
            f'<span class="user-chip owner">{m.name or m.email}</span>'
            for m in metrics.owners
        ])
        
        # Build removed member chips
        removed_chips = "".join([
            f'<span class="user-chip removed">{m.name or m.email}</span>'
            for m in metrics.removed_members
        ]) if metrics.removed_members else '<p style="color: #666;">No removed members</p>'
        
        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #4CAF50, #45a049);">
                Team Membership Overview
            </div>
            <div class="section-content">
                <div class="subsection">
                    <h4>Team Owners ({metrics.owners_count})</h4>
                    <div class="user-list">
                        {owner_chips}
                    </div>
                </div>
                <div class="subsection">
                    <h4>Removed Members ({metrics.removed_members_count})</h4>
                    <div class="user-list">
                        {removed_chips}
                    </div>
                </div>
                <div class="info-box">
                    <p><strong>Total with Access:</strong> {metrics.active_members_count} members</p>
                    <p><strong>Data Source:</strong> Cursor Admin API (/teams/members)</p>
                </div>
            </div>
        </div>
        """
    
    def _build_monthly_usage_section(self, metrics: AdoptionMetrics) -> str:
        """Build the monthly usage statistics section."""
        if not metrics.monthly_stats:
            return ""
        
        # Build table rows (chronological order)
        rows = ""
        for stats in metrics.monthly_stats:
            rows += f"""
            <tr>
                <td>{stats.month_year_str}</td>
                <td>{stats.active_users}</td>
                <td class="requests-cell">{format_number(stats.total_requests, 1)}</td>
                <td>{format_number(stats.total_interactions, 0)}</td>
            </tr>
            """
        
        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #2196F3, #1976D2);">
                Monthly Usage Statistics
            </div>
            <div class="section-content">
                <table>
                    <thead>
                        <tr>
                            <th>Month</th>
                            <th>Active Users</th>
                            <th>Total Requests</th>
                            <th>Interactions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {rows}
                    </tbody>
                </table>
                <div class="info-box">
                    <p><strong>Data Source:</strong> Monthly CSV exports from Cursor Admin Dashboard</p>
                    <p><strong>Active User Definition:</strong> Made at least 1 request in the month</p>
                </div>
            </div>
        </div>
        """
    
    def _build_top_users_section(self, metrics: AdoptionMetrics) -> str:
        """Build the top users leaderboard section."""
        if not metrics.top_users:
            return ""
        
        rows = ""
        for rank, (email, requests) in enumerate(metrics.top_users, 1):
            medal = ""
            if rank == 1:
                medal = "🥇 "
            elif rank == 2:
                medal = "🥈 "
            elif rank == 3:
                medal = "🥉 "
            
            # Get display name (email username)
            display_name = email.split("@")[0].replace(".", " ").title()
            
            rows += f"""
            <tr>
                <td class="rank-cell">{medal}{rank}</td>
                <td>{display_name}</td>
                <td style="color: #666; font-size: 0.85rem;">{email}</td>
                <td class="requests-cell">{format_number(requests, 1)}</td>
            </tr>
            """
        
        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #ff9a56, #ff6b35);">
                Top Users by Request Count
            </div>
            <div class="section-content">
                <table>
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Total Requests</th>
                        </tr>
                    </thead>
                    <tbody>
                        {rows}
                    </tbody>
                </table>
                <div class="info-box">
                    <p><strong>Period:</strong> All available data (Sep 2025 - Present)</p>
                    <p>Requests are summed across all months from CSV data</p>
                </div>
            </div>
        </div>
        """
    
    def _build_inactive_users_section(self, metrics: AdoptionMetrics) -> str:
        """Build the inactive users section."""
        
        def build_inactive_list(users: List[InactiveUserInfo], title: str, count: int) -> str:
            if not users:
                return f"""
                <div class="subsection">
                    <h4>{title} (0)</h4>
                    <p style="color: #4CAF50;">✓ All users with access have been active</p>
                </div>
                """
            
            chips = "".join([
                f'<span class="user-chip inactive" title="Last active: {u.last_activity or "Never"}">'
                f'{u.name or u.email.split("@")[0]}</span>'
                for u in users
            ])
            
            return f"""
            <div class="subsection">
                <h4>{title} ({len(users)})</h4>
                <div class="user-list">
                    {chips}
                </div>
            </div>
            """
        
        # Build never used section
        never_used_content = ""
        if metrics.never_used:
            never_chips = "".join([
                f'<span class="user-chip inactive">{u.name or u.email.split("@")[0]}</span>'
                for u in metrics.never_used
            ])
            never_used_content = f"""
            <div class="subsection">
                <h4>Never Used ({len(metrics.never_used)})</h4>
                <div class="user-list">
                    {never_chips}
                </div>
                <div class="warning-box">
                    <p>These users have active Cursor licenses but have never used the tool.</p>
                    <p>Consider reaching out for onboarding support.</p>
                </div>
            </div>
            """
        
        return f"""
        <div class="section">
            <div class="section-header" style="background: linear-gradient(135deg, #e91e63, #c2185b);">
                Inactive Users Analysis
            </div>
            <div class="section-content">
                {build_inactive_list(metrics.inactive_30_days, "Inactive for 30+ Days", len(metrics.inactive_30_days))}
                {build_inactive_list(metrics.inactive_60_days, "Inactive for 60+ Days", len(metrics.inactive_60_days))}
                {build_inactive_list(metrics.inactive_90_days, "Inactive for 90+ Days", len(metrics.inactive_90_days))}
                {never_used_content}
                <div class="info-box">
                    <p><strong>Reference Date:</strong> {metrics.reference_date}</p>
                    <p>Users listed have active access but no recorded activity in the specified period</p>
                </div>
            </div>
        </div>
        """
